schema_version: 1
task:
  id: task1
  instruction: task1
dataset_ref: ../dataset.yaml
state_schema: real_v1
control_profile_ref: ../controls/spacemouse_extended.yaml
start_pose_ref: ../poses/tasks/remove_objects_from_box_20mm_start.yaml
hand_presets:
  open: ../poses/tasks/remove_objects_from_box_open.yaml
  grasp: ../poses/tasks/remove_objects_from_box_grasp.yaml
  auxiliary_open: ../poses/tasks/remove_objects_from_box_aux_open.yaml
  auxiliary_grasp: ../poses/tasks/remove_objects_from_box_aux_grasp.yaml
